import type { Product, Supplier } from "./types";

export const suppliers: Supplier[] = [
  { id: "s1", name: "Ruggiero S.p.A." },
  { id: "s2", name: "Olearia F.lli Manca" },
  { id: "s3", name: "Pastificio Voiello" },
  { id: "s4", name: "Cantine del Sud" },
  { id: "s5", name: "Macelleria Bianchi" },
  { id: "s-removed", name: "Fornitore rimosso", removed: true },
];

export const initialProducts: Product[] = [
  {
    id: "p1",
    name: "Salsa di Pomodoro S. Marzano",
    unit: "u.",
    supplier_id: "s1",
    current_stock: 45,
    min_threshold: 10,
    max_threshold: 60,
    manual_status_override: null,
    category: "Conserve",
  },
  {
    id: "p2",
    name: "Olio Extra Vergine (5L)",
    unit: "u.",
    supplier_id: "s2",
    current_stock: 2,
    min_threshold: 5,
    max_threshold: 20,
    manual_status_override: null,
    category: "Condimenti",
  },
  {
    id: "p3",
    name: "Spaghetti N.5 (5kg)",
    unit: "u.",
    supplier_id: "s3",
    current_stock: 12,
    min_threshold: 8,
    max_threshold: 30,
    manual_status_override: "YELLOW",
    category: "Pasta",
  },
  {
    id: "p4",
    name: "Avocado Hass (Cassa)",
    unit: "casse",
    supplier_id: "s-removed",
    current_stock: null,
    min_threshold: 3,
    max_threshold: 10,
    manual_status_override: null,
    category: "Frutta",
  },
  {
    id: "p5",
    name: "Vino Rosso della Casa",
    unit: "bot.",
    supplier_id: "s4",
    current_stock: 24,
    min_threshold: 12,
    max_threshold: 48,
    manual_status_override: null,
    category: "Bevande",
  },
  {
    id: "p6",
    name: "Bistecca di Manzo",
    unit: "kg",
    supplier_id: "s5",
    current_stock: 0,
    min_threshold: 4,
    max_threshold: 15,
    manual_status_override: null,
    category: "Carne",
  },
];

export const categories = [
  "Tutti gli articoli",
  "Bevande",
  "Carne",
  "Pasta",
  "Conserve",
  "Condimenti",
  "Frutta",
];